server:
  port: 8765

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: event-service-route
          uri: lb://event-service
          predicates:
            - Path=/api/event/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka